# Can be used to update the environment with the following command:
#
#     conda env update --name dolphin-env --file conda-env-gpu-extras.yml
# https://docs.conda.io/projects/conda/en/latest/commands/update.html
# See also for numba's GPU installation instructions:
# https://numba.pydata.org/numba-doc/latest/user/installing.html#installing-using-conda-on-x86-x86-64-power-platforms
# NOTE: the `cudatoolkit` version must match the CUDA runtime version you have installed
# See the `Getting Started` in the docs
channels:
  - conda-forge
dependencies:
  - cupy>=11.0
  - cudatoolkit
  - pynvml>=11.0
