version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Build dolphin docker image"
          command: |
            docker build . -f Dockerfile
  test:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            conda install -y --file requirements.txt
      - run:
          name: "Install dolphin package"
          command: |
            python -m pip install --no-deps .
      - run:
          name: "Run pytest"
          command: |
            python -m pytest


workflows:
  build-workflow:
    jobs:
      - build
      - test
