name: deploy_docs

on:
  release:
    types: [created]

jobs:
  deploy_docs:
    name: Run tests with pytest
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@v12
      with:
        environment-file: environment.yml
        environment-name: DEVELOP
        channels: conda-forge
        cache-env: true
        cache-env-key: ubuntu-latest-3.10
        extra-specs: |
          python=3.10
    - name: Install package
      run: |
        python -m pip install .[docs]
    - name: Run tests
      run: |
        python docs/deploy_latest_docs.py
