name: Publish Docker 📦 to ghcr.io

# Based on Mintpy:
# https://github.com/insarlab/MintPy/blob/5ca554fef324b816f9130feec567e2cf463e41d2/.github/workflows/build-n-publish-to-pypi.yml

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  dockerize:
    name: Build Docker image and push to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build docker image
        run: |
          bash docker/build-docker-image.sh --tag latest

      - name: Set environment variables for docker build
        run: |
          # Save version number from CLI
          version=$(docker run --rm opera-adt/dolphin:latest dolphin --version)
          sanitized_version=\${version//+/-} # Replace all '+' with '-'
          echo "DOLPHIN_VERSION=\${sanitized_version}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, tag, and push image to Github Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:v${{ env.DOLPHIN_VERSION }}
          labels: |
            org.opencontainers.image.created=${{ env.CI_JOB_TIMESTAMP }}
            org.opencontainers.image.version=${{ env.DOLPHIN_VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Add develop tag
        if: github.ref == 'refs/heads/main'
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ghcr.io/${{ github.repository }}:${{ env.DOLPHIN_VERSION }}
          dst: ghcr.io/${{ github.repository }}:develop

      - name: Add latest tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ghcr.io/${{ github.repository }}:${{ env.DOLPHIN_VERSION }}
          dst: ghcr.io/${{ github.repository }}:latest
