name: Pytest and build docker image

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  # https://github.com/pytest-dev/pytest/issues/2042#issuecomment-429289164
  PY_IGNORE_IMPORTMISMATCH: 1

jobs:
  pytest:
    strategy:
      matrix:
        os:
          - label: Linux
            runner: ubuntu-latest
          - label: macOS
            runner: macos-latest

        deps:
          - label: Latest
            spec: ""
          - label: Minimum
            spec: |
              python=3.8
              gdal=3.5
              h5py=3.6
              h5netcdf=1.1
              isce3=0.8.0
              numpy=1.20
              numba=0.54
              pydantic=1.10
              pymp-pypi=0.4.5
              pyproj=3.3
              rich=12.0
              ruamel_yaml=0.15
              scipy=1.5
              threadpoolctl>=3.0

      fail-fast: false
    name: ${{ matrix.os.label }} • ${{ matrix.deps.label }}
    runs-on: ${{ matrix.os.runner }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: conda-env.yml
          environment-name: dolphin-env
          extra-specs: ${{ matrix.deps.spec }}
          channels: conda-forge
      - name: Install
        run: |
          pip install --no-deps .
      - name: Install test dependencies
        run: |
          micromamba install -f tests/requirements.txt -c conda-forge
      - name: Disable numba for codecov
        # https://community.codecov.com/t/numba-jitted-methods-are-not-captured-by-codecov/2649
        run: |
          echo "NUMBA_DISABLE_JIT=1" >> $GITHUB_ENV
      - name: Test (no numba for codecov)
        run: |
          pytest --cov-report=xml
      - name: Coverage report
        uses: codecov/codecov-action@v2

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: |
          docker build . -t opera-adt/dolphin -f docker/Dockerfile
      - name: Test entrypoint
        run: |
          docker run --rm opera-adt/dolphin
